### ISSUE TITLE
Fix binary output

### ISSUE THREAD

**Issue by weaverba137** [astro-datalab/fits2db#1]
Various documents say that `fits2db` should produce binary output.  For example, this snippet from the "ingest party" tutorial.
```
fits2db --sql=p --create --drop \  # create table
    -B -t mytable file01.fits | psql tapdb datalab
fits2db --sql=p -C -B -t mytable file02.fits | psql tapdb datalab
fits2db --sql=p -C -B -t mytable file03.fits | psql tapdb datalab
```
However, when I tried to run this last summer, only ASCII output worked.  There was a discussion on Slack at the time (See August 7, 2018 and subsequent in `#queries`).  The initial indications were that the ordering of SQL commands in the binary output may have been a factor, especially when used with `--truncate`.  I can't find a record of any other bug report, so now I'm creating one.

**Comment by mjfitzpatrick** [comment]
I think this is now closed with the latest PR.  Please reopen if it comes back again
