### ISSUE TITLE
Allow random_id columns to follow the FITS/SQL ordering 

### ISSUE THREAD

**Issue by weaverba137** [astro-datalab/fits2db#2]
According to some notes from summer 2018, "When `fits2db` adds the `random_id` column, it does not obey the ordering of the FITS file or the SQL file."  Given that `fits2db` has knowledge of both the FITS file and the SQL table, it seems like it should be possible to perform this ordering.  This is probably particularly important for loading in binary mode.

**Comment by mjfitzpatrick** [comment]
I'm not sure from where the 2018 comment is derived, but FITS2DB doesn't currently have the ability to type-order the columns.   The random_id and serial_id options simply append columns to each row of the table.  A type-ordering option is planned but would require a major refactoring of the code and isn't a priority at the moment.
