### ISSUE TITLE
not looking for file in CWD

### ISSUE THREAD

**Issue by acscott** [astro-datalab/fits2db#7]
This is a new bug, from a freshly compiled/installed fits2db on db03 (CentOS 8).
see the repo as root at `db03:/root/fits2db`

It seems to not look for the input FITS file in the CWD.

To reproduce the bug:

On db03:
```cd /net/dl2/data/decals/dr9_load/north/000_n
fits2db --sql=p --create --drop --rid=random_id -C -X -t test tractor-0001m002.fits
```
It will not output the psql copy command for the file, but if we use  `./tractor-0001m002.fits` it will.

The latest cfitsio 3.49 was installed on here as well:  `/root/cfitsio-3.49`

**Comment by mjfitzpatrick** [comment]
FITS2DB problem was a change in behavior of the strcmp() libc function, it was indeed being used incorrectly but was harmless on earlier versions.  Fixed in repo, not deployed to db03 since binary is currently in use.
